# Generated by Django 5.1.5 on 2025-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0024_alter_profile_profileowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Profileowner',
        ),
    ]
