# Generated by Django 5.1.5 on 2025-03-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0030_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
