# Generated by Django 5.1.5 on 2025-03-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0035_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='SUb',
        ),
    ]
